### ISSUE TITLE
Enabling sync triggers NullReferenceException and crash

### ISSUE THREAD

**Issue by joh** [tomboy-notes/tomboy.osx#42] opened 2014-11-25 21:55 UTC
Tried to enable sync folder via the preferences dialog, and Tomboy immediately crashes:

```
./Tomboy
[DEBUG 22:51:14.107] Backup Path set to /Users/joh/Library/Application Support/Tomboy/v1
[DEBUG 22:51:14.218] cache directory set to /Users/joh/Library/Caches/Tomboy
2014-11-25 22:51:17.193 Tomboy[86834:d07] Could not connect the action SyncURL: to target of class SyncPrefDialogController
2014-11-25 22:51:17.194 Tomboy[86834:d07] Could not connect the action exportNotes: to target of class SyncPrefDialogController

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
at Tomboy.Sync.SettingsSync.Write (System.Xml.XmlWriter,Tomboy.Sync.SettingsSync) <0x00071>
at Tomboy.Sync.SettingsSync.Write (Tomboy.Sync.SettingsSync) <0x00067>
at Tomboy.SyncPrefDialogController.SetSyncPath (MonoMac.Foundation.NSObject) <0x0031b>
at (wrapper dynamic-method) object.[Tomboy.SyncPrefDialogController.Void SetSyncPath(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject) <0x00033>
at (wrapper native-to-managed) object.[Tomboy.SyncPrefDialogController.Void SetSyncPath(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject) <0x0011f>
at (wrapper managed-to-native) MonoMac.AppKit.NSApplication.NSApplicationMain (int,string[]) <0x00012>
at MonoMac.AppKit.NSApplication.Main (string[]) <0x00097>
at Tomboy.MainClass.Main (string[]) <0x00017>

[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
at Tomboy.Sync.SettingsSync.Write (System.Xml.XmlWriter,Tomboy.Sync.SettingsSync) <0x00071>
at Tomboy.Sync.SettingsSync.Write (Tomboy.Sync.SettingsSync) <0x00067>
at Tomboy.SyncPrefDialogController.SetSyncPath (MonoMac.Foundation.NSObject) <0x0031b>
at (wrapper dynamic-method) object.[Tomboy.SyncPrefDialogController.Void SetSyncPath(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject) <0x00033>
at (wrapper native-to-managed) object.[Tomboy.SyncPrefDialogController.Void SetSyncPath(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject) <0x0011f>
at (wrapper managed-to-native) MonoMac.AppKit.NSApplication.NSApplicationMain (int,string[]) <0x00012>
at MonoMac.AppKit.NSApplication.Main (string[]) <0x00097>
at Tomboy.MainClass.Main (string[]) <0x00017>
```

Running tomboy.osx-0.3.4 and MonoFramework-MRE-3.10.0.macos10.xamarin.x86.

**Comment by rashoodkhan** [comment] 2015-04-18 07:59
@joh - The issue is fixed on the master branch. Thanks!

**Closed by rashoodkhan** 2015-04-18 07:59 UTC
Labels: bug
